
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND ASSIGNATION COMMA DECREASE DIFFERENT DIVISION DOUBLE ELSE EQUALS FALSE FOR FUNCTION GREATER GREATEREQUAL IF INCREASE INT LEFTBRACKET LEFTKEY LEFTPAR LESSER LESSEREQUAL METODO MULTIPLICATION NAME NEWLINE OR PRINT PRIVATE PUBLIC READ RETURN RIGHTBRACKET RIGHTKEY RIGHTPAR SEMICOLON STRING SUBSTRACTION SUM TRUE VARDECLARATION VOID WHILEgrammar : grammar2 INTgrammar : grammar2 errorgrammar2 : NAME ASSIGNATIONinstruction : metodometodo : number_assignations ASSIGNATION METODO LEFTPAR INT RIGHTPARmetodo : NAME ASSIGNATION METODO LEFTPAR INT errornumber_assignations : NAMEnumber_assignations : NAME COMMA NAMEnumber_assignations : NAME COMMA NAME COMMA NAMEnumber_assignations : NAME COMMA NAME COMMA NAME COMMA NAME COMMAnumber_assignations : NAME COMMA NAME COMMA NAME COMMA NAME COMMA NAMEnumber_assignations : NAME error NAME COMMA NAME COMMA NAME COMMA NAME'
    
_lr_action_items = {'NAME':([0,],[3,]),'$end':([1,4,5,],[0,-1,-2,]),'INT':([2,6,],[4,-3,]),'error':([2,6,],[5,-3,]),'ASSIGNATION':([3,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'grammar':([0,],[1,]),'grammar2':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> grammar","S'",1,None,None,None),
  ('grammar -> grammar2 INT','grammar',2,'p_grammar1','parse.py',14),
  ('grammar -> grammar2 error','grammar',2,'p_grammar1_error','parse.py',17),
  ('grammar2 -> NAME ASSIGNATION','grammar2',2,'p_grammar2','parse.py',21),
  ('instruction -> metodo','instruction',1,'p_INSTRUCTION','parse.py',24),
  ('metodo -> number_assignations ASSIGNATION METODO LEFTPAR INT RIGHTPAR','metodo',6,'p_METODO','parse.py',27),
  ('metodo -> NAME ASSIGNATION METODO LEFTPAR INT error','metodo',6,'p_METODO_error','parse.py',33),
  ('number_assignations -> NAME','number_assignations',1,'p_NUMBER_ASSIGNATIONS1','parse.py',38),
  ('number_assignations -> NAME COMMA NAME','number_assignations',3,'p_NUMBER_ASSIGNATIONS2','parse.py',41),
  ('number_assignations -> NAME COMMA NAME COMMA NAME','number_assignations',5,'p_NUMBER_ASSIGNATIONS3','parse.py',44),
  ('number_assignations -> NAME COMMA NAME COMMA NAME COMMA NAME COMMA','number_assignations',8,'p_NUMBER_ASSIGNATIONS4','parse.py',47),
  ('number_assignations -> NAME COMMA NAME COMMA NAME COMMA NAME COMMA NAME','number_assignations',9,'p_NUMBER_ASSIGNATIONS5','parse.py',50),
  ('number_assignations -> NAME error NAME COMMA NAME COMMA NAME COMMA NAME','number_assignations',9,'p_NUMBER_ASSIGNATIONS5_error','parse.py',53),
]
